### ISSUE TITLE
Quest "Adobe", only completable with schist?

### ISSUE THREAD

**Issue by rangerrambo** [teagan75/TG-Terrafirmacraft#2]
I started in a biome were marble is top rock, was just wondering, if it was intended for players to look for schist or can it be done to where mutliple rock types are accepted?

http://i.imgur.com/Zb6jLyT.png

Going through the quests atm, great pack so far!

**Comment by teagan75** [comment]
Unfortunately there are a few quests that need to be specific due to the mod dev not using the ore dictionary or meta data correctly. For those quests I used what was available to those using the beginner map in the template folder. 

If (in the quest book) the bricks aren't flipping through a few other choices, this would be the reason.

**Comment by rangerrambo** [comment]
Ah completely forgot the was a beginner map. I guess I'll restart my progress with that one. Thank you!

**Comment by teagan75** [comment]
Your welcome. You don't necessarily need to restart. There is a good chance you will run into schist later on to complete that quest.  Glad you are enjoying the pack tho.

**Comment by rangerrambo** [comment]
Ya, I while I am not a new player (played TFC in FTBs Technofirma craft), I like this pack much much better, especially for new players.

If you would like I can report more things (and bugs), where it could possibly be confusing for the new player (example: I know there are quests on making molds for pickaxe/saw and such, but seems there is a jump in blacksmith questline, where it assumes you know how to make copper ingots.

**Comment by teagan75** [comment]
I will check on the ingot making and molds. Go ahead and report any bugs and or suggestions here. I would just ask that you make a separate issue so I can keep track.
