### ISSUE TITLE
What was the easiest way to set up a home server?

### ISSUE THREAD

**Issue by rangerrambo** [teagan75/TG-Terrafirmacraft#3]
I was looking at doing some of this http://wiki.terrafirmacraft.com/Installation#Server_Installation

and then copying configs/mods folders from your pack. Would that work or am I missing something?

If there is a simpler way with curse would love to know.

**Comment by teagan75** [comment]
That will work, you can also get the whole server package here https://minecraft.curseforge.com/projects/teagans-guide-to-terrafirmacraft-squad-network/files/2344774
scroll to the bottom

**Comment by rangerrambo** [comment]
Thanks!, think I got it working. But don't think the old AMD 64 6000+ with 4gigs of ram as dedicated server will do the job for 2 people, unless there is other optimizations to be done.

I tried running forge universal.jar alone and bat file as described in the wiki, but think the avg tick at 20000ms is a bit too high.

**Comment by teagan75** [comment]
Are you using any Java arguments?

**Comment by teagan75** [comment]
Wait. Your computer has 4 gigs total? Or you allocated 4gigs to the server?  You almost need the latter.

**Comment by rangerrambo** [comment]
Ya its a 2nd pc I have with 4 gigs total memory. I just thought I try the dedicated server on that first, instead of my i5 with 8gigs total.

I tried with the arguments in the wiki so "java -Xmn1G -Xms2G -Xmx2G -jar forge-1.7.10-10.13.4.1558-1.7.10-universal.jar" and fixed the version of the correct jar fire.

**Comment by rangerrambo** [comment]
Actually, It is ok for first measure. Will probably migrate it to a different computer. Thanks for help!
