### ISSUE TITLE
Cooked food as reward corruption

### ISSUE THREAD

**Issue by Azreil** [teagan75/TG-Terrafirmacraft#4]
Hey I have created a cellar and been playing for a few hours no problem, but now I'm getting a stack trace error with one of the shelves. I removed the contents before a crash but now it crashes at world load. Its contents were some of the "grain" food items. Grains, Flours, and Breads. some were at low rot, and others weren't. My Meats shelf and Vegies Shelf were just fine even with almost  rotten foods.
I have the error log if you want to look at it.
[crash-2016-12-06_16.12.31-server.txt](https://github.com/teagan75/TG-Terrafirmacraft/files/635137/crash-2016-12-06_16.12.31-server.txt)

**Comment by teagan75** [comment]
Forwarded the crash report to mod dev. Do you have a world editor like MCEdit? If so you can load the world, goto the coords and remove the item. The coords are 100,142,-12238 and the item ID is 885

**Comment by Azreil** [comment]
I havent installed it yet. Just wanted to let you know about some weird bug. Love the pack and will continue looking for bugs. Dont want you and modii101 crashing In videos. ;)

**Comment by teagan75** [comment]
Hehe yeah that would be bad but I can fix the world if that happens. Question: the smoked meat is what is corrupted. Did you use meat you hunted or got as a reward? Curious if something got corrupted through the questbook.

**Comment by Azreil** [comment]
Thats the weird part. That location had the grains. I did leave one of the breads in for to long. It was very dark. Lol it was the one mostly rotten it was about 20-30%.

**Comment by teagan75** [comment]
That is really strange. Another option, if you don't know how to use MCEdit is to restore a backup dated/time stamped before your crash.

**Comment by Azreil** [comment]
I do. I make packs and have run servers in the past. I will attempt to resolve the issue on my end. If i get a perm fix i will send you the files and report them to the auther.

**Comment by teagan75** [comment]
Thanks for your help and sorry about that. Hopefully it won't happen again.

**Comment by Azreil** [comment]
Its not the shelf, I replaced them using chests and it still happened. It was one of the grains causing a tick bug. It was either the Cooked Cornbread, the Cooked Oat Bread, or both. I got them from the "Making Dough pt. 4" quest. It seems to be an issue with the decay feature of the modpack. I'm not much of a coder myself, but it did give a a line trace on the position within the chest and one of those was in that spot. I will delete the items and wait to see if it crashes again or if something else causes it.
Best suggestion try to keep all your food from going into the red. That's usually when I see the crash.

**Comment by teagan75** [comment]
My suspicion is that somehow the food item you got as a reward is corrupting. I have had no issues with decaying food when I just play tfc without the guide. I will look into this more. Thanks

**Comment by Azreil** [comment]
NP, I know its hard testing everything when its just you. I am glad to help. I really enjoy this pack even with crashing 30 times testing for issues. lol
I like doing things like this and I don't have friends to help with my pack and my youtube only has 3 subs. Not many people see my pack. it did get 200 downloads in the first 2 weeks though. :)

**Comment by teagan75** [comment]
I have changed the reward for the "Making Dough pt. 4" quest from cooked bread to a selection of grains to choose from. The cooking is very complex in TFC so I think the quest book can't handle all the nbt data that can be attached to cooked food. Will push an update after checking all the quests for similar issues.

**Comment by teagan75** [comment]
Pushed update 1.2 to Curse with the reward changed.
