### ISSUE TITLE
Issues with starting

### ISSUE THREAD

**Issue by NeekotheFoxx** [teagan75/TG-Terrafirmacraft#6]
When loading, better questing keeps popping up and saying "objective complete, new quest" and it wont go away even after completing the first quest. It keeps flashing on the screen and making the quest completion sound. 

Also i dont have a boat

**Comment by teagan75** [comment]
That is a known bug which I thought was fixed. It is just annoying. The boat is in the Beginner map found in the template folder or you can get it from the Curse launcher

**Comment by NeekotheFoxx** [comment]
I downloaded the pack from the launcher. Is there anything I can do on my end to fix the quest bug?

**Comment by teagan75** [comment]
There is nothing you can do to fix the quest notification spamming. It is more annoying and won't break anything. It usually goes away after a while.
