### ISSUE TITLE
TFC crash

### ISSUE THREAD

**Issue by weightlessrose** [teagan75/TG-Terrafirmacraft#7]
[crash-2017-03-06_15.35.24-server.txt](https://github.com/teagan75/TG-Terrafirmacraft/files/823225/crash-2017-03-06_15.35.24-server.txt)

**Comment by teagan75** [comment]
A couple of questions: did you download the newest version of tfc? There is something causing a tick error in a container. Do you remember what item you last placed ina container and was it a quest reward?

**Comment by weightlessrose** [comment]
I was placing dirt  I got in creative to fill a hole so I could have an area for my fruit trees. I was in survival when it crashed. I don't believe I have the latest version, it has not notified me of any, could be late, it happens sometimes
